'use strict';
let state, view='dashboard', filter='all', search='', previewData=null;
const titles={dashboard:'แจ้งเตือนการเบิกยา',refill:'บันทึกประวัติการเบิก',import:'นำเข้ายอดใช้จริง',settings:'ตั้งค่าและสำรอง'};
const labels={no_pack:'ยังไม่ตั้งขนาดแพ็ค',first_order:'แนะนำเบิกครั้งแรก',urgent:'ถึงรอบเบิก',today:'ควรเบิกภายใน 2 วัน',near:'ใกล้ถึงรอบเบิก',ok:'ยังไม่ถึงรอบ',no_usage:'ไม่มีการใช้ย้อนหลัง'};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,dec=0)=>v===null||v===undefined?'—':Number(v).toLocaleString('th-TH',{maximumFractionDigits:dec});
const today=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const pretty=d=>d?new Date(d+'T00:00:00').toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}):'ยังไม่มีข้อมูล';
async function api(path,data){if(window.OfflineStock?.enabled())return OfflineStock.api(path,data);let opts=data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Stock-App':'1'},body:JSON.stringify(data)};let r=await fetch(path,opts),text=await r.text(),j;try{j=JSON.parse(text)}catch(_){throw Error('ไม่สามารถเชื่อมต่อฐานข้อมูล กรุณาเปิดระบบด้วย start-web.bat')};if(!r.ok)throw Error(j.error||'บันทึกไม่สำเร็จ');return j}
function message(text,error=false){$('#message').innerHTML=text?`<div class="notice ${error?'error':'teal'}">${esc(text)}</div>`:''}
async function load(){try{state=await api('/virtual-stock/api/state?date='+$('#asof').value);render()}catch(e){message(e.message,true)}}
function options(selected){return state.rows.map(r=>`<option value="${r.id}" ${r.id==selected?'selected':''}>${esc(r.name)} · ${esc(r.unit)}</option>`).join('')}
function badge(r){return `<span class="badge ${r.status}">${labels[r.status]}</span>`}
function centralNotice(){
 if(!state.onlineMode)return '';
 let c=state.central||{state:'error',message:'ยังไม่ได้เชื่อมต่อฐานข้อมูลกลาง'},ok=c.state==='ready';
 return `<div class="notice ${ok?'teal':'error'}"><b>${ok?'ฐานข้อมูลกลางเชื่อมต่อแล้ว':'ฐานข้อมูลกลางยังไม่พร้อม'}</b> · ${esc(c.message)}${ok?' · ข้อมูลทุกเครื่องใช้ชุดเดียวกัน':' · เปิดหน้า <a href="#" data-go="settings">ตั้งค่าและสำรอง</a> เพื่อตรวจสอบการเชื่อมต่อ'}</div>`;
}
function dashboard(){
 let counts=Object.fromEntries(Object.keys(labels).map(s=>[s,state.rows.filter(r=>r.status===s).length]));
 let stale=state.last!==state.asof;
 return `${centralNotice()}${stale||state.missing7||state.missing30?`<div class="notice">ข้อมูลการใช้ล่าสุด ${pretty(state.last)} · วันที่ยังไม่ได้ยืนยันข้อมูลครบ: 7 วันล่าสุด ${state.missing7} วัน / 30 วันล่าสุด ${state.missing30} วัน<br>วันที่ไม่มีรายการถูกคิดเป็น 0 จึงอาจทำให้อัตราใช้ต่ำกว่าจริง หากข้อมูลยังขาด วันคาดการณ์รอบเบิกอาจคลาดเคลื่อน <a href="#" data-go="import">ตรวจสอบข้อมูลการใช้</a></div>`:''}
 ${counts.no_pack?`<div class="notice"><b>${counts.no_pack} รายการยังไม่ได้กำหนดขนาดแพ็ค</b> · กรุณาระบุจำนวนหน่วยย่อยต่อ 1 แพ็คก่อน ระบบจึงจะคำนวณจำนวนแพ็คที่ควรเบิกได้ <a href="#" data-go="settings">ตั้งขนาดแพ็ค</a></div>`:''}
 ${counts.first_order?`<div class="notice teal"><b>${counts.first_order} รายการพร้อมเริ่มระบบ</b> · จำนวนเบิกครั้งแรกคำนวณจากอัตราใช้จริงสำหรับ ${n(state.settings.target)} วัน เมื่อบันทึกการเบิกแล้ว ระบบจะปรับรอบจากประวัติจริงโดยอัตโนมัติ</div>`:''}
 <div class="cards">${['no_pack','first_order','urgent','today','near','ok'].map(s=>`<button type="button" class="card ${s}" data-status-card="${s}" aria-label="ดูรายการ ${labels[s]} ${counts[s]} รายการ"><span>${labels[s]}</span><strong>${counts[s]}</strong><small>รายการ</small></button>`).join('')}</div>
 <div class="panel" id="stock-list"><div class="split-title"><h2>รายการคาดการณ์รอบเบิกยา</h2><span class="progress">เริ่มจากยอดใช้จริง แล้วเรียนรู้จากประวัติเบิก</span></div><div class="toolbar"><input id="search" type="search" placeholder="ค้นหาชื่อยา" aria-label="ค้นหาชื่อยา" value="${esc(search)}"><select id="filter" aria-label="กรองสถานะ"><option value="all">ยาทั้งหมด</option><option value="action" ${filter==='action'?'selected':''}>รายการที่ควรดำเนินการ</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${filter===k?'selected':''}>${v}</option>`).join('')}</select><a class="button secondary" href="/virtual-stock/api/export?date=${state.asof}">ส่งออกรายการ CSV</a></div><div class="table-wrap"><table><thead><tr><th>ยา / หน่วยใช้</th><th>สถานะ</th><th>เบิกล่าสุด</th><th class="num">ถึงรอบใน (วัน)</th><th class="num">อัตราใช้/วัน (หน่วย)</th><th class="num">หน่วย/แพ็ค</th><th class="num">รอบที่แนะนำ (วัน)</th><th class="num">แนะนำเบิก</th><th></th></tr></thead><tbody id="drug-table"></tbody></table></div></div>`;
}
function table(){let priority={no_pack:0,first_order:1,urgent:2,today:3,near:4,ok:5,no_usage:6};let rows=state.rows.filter(r=>r.name.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter===r.status||(filter==='action'&&['no_pack','first_order','urgent','today','near'].includes(r.status)))).sort((a,b)=>priority[a.status]-priority[b.status]||(a.days_until??Infinity)-(b.days_until??Infinity));$('#drug-table').innerHTML=rows.map(r=>`<tr><td class="name">${esc(r.name)}<small>${esc(r.unit)} · ใช้จริงเฉลี่ย 7 วัน ${n(r.avg7,1)} / 30 วัน ${n(r.avg30,1)}</small></td><td>${badge(r)}</td><td>${pretty(r.last_refill)}<small class="muted">${r.last_refill?` · ${n(r.last_refill_qty,2)} ${esc(r.unit)}`:''}</small></td><td class="num">${n(r.days_until,0)}${r.expected?`<small class="muted"> · ${pretty(r.expected)}</small>`:''}</td><td class="num">${n(r.rate,1)}</td><td class="num">${r.pack_set?n(r.pack,2):'—'}</td><td class="num">${n(r.order_cycle_days,1)}</td><td class="num"><b>${r.recommended_packs===null?'—':n(r.recommended_packs)+' แพ็ค'}</b>${r.recommended_units!==null?`<small class="muted"> · ${n(r.recommended_units)} ${esc(r.unit)}</small>`:''}</td><td>${r.pack_set?`<button class="secondary small" data-refill="${r.id}">บันทึกเบิก</button>`:`<button class="secondary small" data-go="settings">ตั้งขนาดแพ็ค</button>`}</td></tr>`).join('')||'<tr><td colspan="9" class="empty">ไม่พบรายการตามเงื่อนไข</td></tr>'}
function refill(selected){return `<div class="panel"><div class="split-title"><div><h2>นำเข้าไฟล์บันทึกการเบิก</h2><p>ดาวน์โหลดรายการที่ระบบแนะนำ นำไปใช้เบิกจริง แล้วแก้คอลัมน์ <b>จำนวนแพ็ค</b> ให้ตรงกับที่เบิก ก่อนอัปโหลดไฟล์กลับเข้าระบบครั้งเดียว</p></div><a class="button secondary" href="/virtual-stock/api/refill-template?date=${state.asof}">ดาวน์โหลดรายการเบิก CSV</a></div><div class="notice">รองรับไฟล์ <b>.xlsx</b> หรือ <b>.csv UTF-8</b> ที่มีคอลัมน์ วันที่เบิก · ยา · จำนวนแพ็ค ระบบจะแสดงตัวอย่างให้ตรวจสอบก่อนบันทึก</div><input id="refill-import-file" type="file" accept=".xlsx,.csv" aria-label="เลือกไฟล์บันทึกการเบิก"><div id="refill-import-preview"></div></div><div class="forms"><div class="panel"><h2>บันทึกรายการตกหล่นทีละรายการ</h2><p class="muted">ใช้ส่วนนี้เฉพาะเมื่อมีรายการเพิ่มเติมหรือจำเป็นต้องแก้ไขเป็นรายตัว</p><form id="refill-form" class="form"><label>ยา<select name="drug" id="refill-drug">${options(selected)}</select></label><div id="refill-hint" class="notice teal"></div><label>วันที่เบิก<input name="day" type="date" value="${today()}" max="${today()}" required></label><label>จำนวนที่เบิก (แพ็ค)<input name="packs" type="number" min="1" step="1" required></label><label>หมายเหตุ<input name="note" maxlength="500" placeholder="เลขใบเบิก / ผู้บันทึก"></label><button>บันทึกการเบิก</button></form></div><div class="panel"><h2>ข้อมูลที่ระบบนำไปคำนวณ</h2><p>ยอดใช้จริงรายวันเป็นข้อมูลหลัก ระบบเลือกค่าเฉลี่ยที่สูงกว่าระหว่าง 7 และ 30 วัน แล้วเผื่อ Safety Stock เพื่อคำนวณจำนวนเบิก</p><p>ประวัติเบิกก่อนวันเริ่มระบบใช้เรียนรู้รอบและจำนวนเท่านั้น เมื่อมีรายการเบิกหลังวันเริ่มระบบ ระบบจะคาดวันถึงรอบจากจำนวนที่เบิกจริงครั้งล่าสุดเทียบกับอัตราใช้</p><p>หากยังไม่มีรายการเบิกหลังวันเริ่มระบบ ระบบจะแสดง “แนะนำเบิกครั้งแรก” แทนการนำวันเบิกเก่ามาคำนวณจนติดลบ</p><p class="muted">ระบบไม่ใช้ยอดคงเหลือหน้าชั้นหรือยอดคงคลังในการคำนวณ</p></div></div><div class="panel"><h2>ประวัติการเบิกยา</h2><div class="table-wrap"><table><thead><tr><th>วันที่</th><th>ยา</th><th class="num">จำนวน</th><th>หมายเหตุ</th><th>สถานะ</th></tr></thead><tbody>${state.refills.map(r=>`<tr><td>${pretty(r.day)}</td><td class="name">${esc(r.name)}</td><td class="num">${r.source_qty!==null&&r.source_qty!==undefined?`${n(r.source_qty,2)} ${esc(r.source_unit)}<small class="muted"> · ตามไฟล์ต้นฉบับ ${esc(r.source_file||'')}</small>`:r.packs?`${n(r.packs)} แพ็ค <small class="muted">(${n(r.qty,2)} ${esc(r.unit)})</small>`:`${n(r.qty,2)} ${esc(r.unit)}`}</td><td>${esc(r.note)}</td><td>${r.voided?'<span class="muted">ยกเลิกแล้ว</span>':`<button class="danger small" data-void="${r.id}">ยกเลิกรายการ</button>`}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">ยังไม่มีประวัติเบิกยา</td></tr>'}</tbody></table></div></div>`}
function hint(){let r=state.rows.find(r=>r.id==$('#refill-drug').value);$('#refill-hint').innerHTML=`${badge(r)}<br>เบิกล่าสุด ${pretty(r.last_refill)} ${r.last_refill?`· ${n(r.last_refill_qty,2)} ${esc(r.unit)}`:''}<br>แนะนำครั้งนี้ ${r.recommended_packs===null?'—':n(r.recommended_packs)+' แพ็ค'} ${r.recommended_units!==null?`(${n(r.recommended_units)} ${esc(r.unit)})`:''} · คาดว่าถึงรอบ ${pretty(r.expected)}`}
function imports(){return `<div class="panel"><h2>นำเข้า Excel สรุปยอดใช้จริง</h2><p>ใช้ไฟล์แบบเดิมที่มีคอลัมน์ <b>วันที่ · ยา · จำนวน</b> หรือ CSV UTF-8 ชื่อคอลัมน์เหมือนกัน ระบบรวมรายการซ้ำเป็นยอดใช้จริงต่อยาแต่ละวัน</p><div class="notice">ไฟล์ต้องเป็น <b>ยอดใช้จริงครบทั้งวันของห้องยา</b> หากมีวันที่เคยนำเข้าแล้ว ระบบจะแทนยอดทั้งวันหลังยืนยัน เพื่อไม่นับยอดซ้ำ ห้ามใช้ไฟล์ที่มีข้อมูลเพียงบางส่วนของวัน</div><input id="import-file" type="file" accept=".xlsx,.csv" aria-label="เลือกไฟล์ยอดใช้จริง"><div id="import-preview"></div></div><div class="panel"><h2>ยืนยันวันที่ข้อมูลการใช้ครบ</h2><p class="muted">ใช้เมื่อได้ตรวจแล้วว่าช่วงนี้นำเข้าครบทุกวัน และวันที่ไม่มีรายการหมายถึงไม่มีการใช้ยา เช่น วันปิดห้องยา การยืนยันนี้ไม่เปลี่ยนยอดใช้จริงที่มีอยู่</p><form id="coverage-form" class="form"><label>ตั้งแต่<input name="first" type="date" max="${today()}" required></label><label>ถึง<input name="last" type="date" max="${today()}" required></label><label class="checkbox"><input type="checkbox" required>ตรวจสอบแล้วว่าไม่มีข้อมูลการใช้ตกหล่นในช่วงนี้</label><button>ยืนยันข้อมูลครบ</button></form></div><div class="panel"><h2>ประวัตินำเข้า</h2><div class="table-wrap"><table><thead><tr><th>ไฟล์</th><th>บันทึกเมื่อ</th><th>รายละเอียด</th></tr></thead><tbody>${state.imports.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.created.replace('T',' '))}</td><td><details><summary>ดูสรุป</summary><pre>${esc(JSON.stringify(JSON.parse(r.detail),null,2))}</pre></details></td></tr>`).join('')}</tbody></table></div></div>`}
function centralSettings(){
 if(!state.onlineMode)return '';
 let s=window.OfflineStock?.status?.()||{};
 return `<div class="panel"><h2>ฐานข้อมูลกลาง</h2><div class="notice ${s.state==='ready'?'teal':'error'}"><b>${s.state==='ready'?'เชื่อมต่อแล้ว':'ยังไม่พร้อม'}</b> · ${esc(s.message||'ยังไม่ได้ตรวจสอบ')}</div><p>ระบบใช้ Google Sheets และ Apps Script ชุดเดียวกับระบบอื่นในหน้า Hub ข้อมูลจึงตรงกันทุกเครื่องโดยไม่มีค่าบริการโฮสต์ฐานข้อมูล</p><form id="central-form" class="form"><label>Apps Script Web App URL<input name="url" type="url" value="${esc(s.endpoint||'')}" required></label><label>API key<input name="key" type="password" placeholder="เว้นว่างเพื่อใช้ค่าที่บันทึกไว้"></label><button>บันทึกและทดสอบการเชื่อมต่อ</button><button type="button" class="secondary" id="central-refresh">โหลดข้อมูลล่าสุดจากส่วนกลาง</button></form><p class="muted">หากขึ้นว่า Apps Script เป็นเวอร์ชันเก่า ให้คัดลอกโค้ด Apps Script ล่าสุดจากหน้าตั้งค่าระบบรายงานยา แล้ว Deploy เป็น New version</p></div>`;
}
function settings(){return `<div class="forms"><div class="panel"><h2>อัตราเผื่อและวันเริ่มระบบ</h2><form id="settings-form" class="form"><label>วันที่เริ่มใช้ระบบ<input name="start" type="date" value="${state.settings.start}" max="${today()}" required></label><label>Safety Stock (%)<input name="safety" type="number" min="0" max="500" step="any" value="${state.settings.safety}" required></label><label>รอบเบิกเริ่มต้น (วัน)<input name="target" type="number" min="1" max="90" step="1" value="${state.settings.target}" required></label><button>บันทึกการตั้งค่า</button></form><p class="muted">รายการเบิกก่อนวันเริ่มระบบใช้เป็นประวัติสำหรับเรียนรู้เท่านั้น และไม่ถูกนำมาเป็นยอดตั้งต้นของรอบปัจจุบัน</p></div><div class="panel"><h2>สูตรที่ใช้</h2><p>อัตราใช้ต่อวัน = ค่าที่สูงกว่าระหว่างยอดใช้จริง 7 วัน ÷ 7 และยอดใช้จริง 30 วัน ÷ 30 แล้วคูณ (1 + Safety Stock ÷ 100)</p><p>รอบแนะนำ = ระยะห่างเฉลี่ย 3 ช่วงล่าสุด หรือรอบเริ่มต้นหากข้อมูลยังไม่พอ</p><p>จำนวนแนะนำแต่ละรอบ = อัตราใช้ต่อวัน × รอบแนะนำ แล้วปัดขึ้นเป็นแพ็คเต็ม</p><p>วันที่คาดว่าถึงรอบ = วันที่เบิกจริงหลังเริ่มระบบ + จำนวนวันที่ปริมาณครั้งล่าสุดน่าจะใช้ได้ โดยไม่เกินรอบแนะนำ</p><p>เมื่อการใช้เพิ่มขึ้น จำนวนแนะนำจะเพิ่มและวันเตือนจะมาเร็วขึ้น</p><p class="muted">ถึงรอบเบิก: วันนี้หรือเลยกำหนด · ควรเบิก: ภายใน 2 วัน · ใกล้ถึงรอบ: ภายใน 3 วัน · ยังไม่ถึงรอบ: มากกว่า 3 วัน ระบบไม่ใช้ยอดคงเหลือ</p></div></div>${centralSettings()}<div class="panel"><h2>ขนาดบรรจุต่อแพ็ค</h2><p>ระบุจำนวนหน่วยย่อยใน 1 แพ็ค เช่น 1 กล่องมี 100 เม็ด ให้กรอก 100</p><div class="notice teal">ประวัติเบิกเดิมที่ระบุหน่วยเป็นกล่องจะถูกแปลงเป็นหน่วยใช้ย้อนหลังให้อัตโนมัติ เมื่อบันทึกขนาดแพ็คของยานั้น</div><form id="packs-form"><div class="table-wrap"><table><thead><tr><th>ยา / หน่วยใช้</th><th class="num">จำนวนหน่วยต่อ 1 แพ็ค</th></tr></thead><tbody>${state.rows.map(r=>`<tr><td class="name">${esc(r.name)}<small>${esc(r.unit)}</small></td><td class="num"><input name="pack_${r.id}" type="number" min="0.000001" step="any" value="${r.pack_set?r.pack:''}" placeholder="ยังไม่ตั้งค่า" aria-label="หน่วยต่อแพ็ค ${esc(r.name)}"></td></tr>`).join('')}</tbody></table></div><button style="margin-top:16px">บันทึกขนาดแพ็คที่กรอก</button></form></div><div class="panel"><h2>สำรองข้อมูล</h2><p>ดาวน์โหลดฐานข้อมูลยอดใช้จริง ประวัติเบิก และประวัติแก้ไข เก็บไว้ก่อนเปลี่ยนเครื่อง</p><a class="button secondary" href="/virtual-stock/api/backup">ดาวน์โหลดฐานข้อมูลสำรอง</a><p class="muted" style="margin-top:14px">กู้คืน: ปิดระบบก่อน แล้วแทนไฟล์ data/stock.sqlite3 ด้วยไฟล์สำรอง (เก็บไฟล์เดิมไว้ก่อน)</p></div>`}
function render(selected){$('#title').textContent=titles[view];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===view));$('#content').innerHTML=({dashboard,refill:()=>refill(selected),import:imports,settings}[view])();if(view==='dashboard'){table();$('#search').oninput=e=>{search=e.target.value;table()};$('#filter').onchange=e=>{filter=e.target.value;table()};document.querySelectorAll('[data-status-card]').forEach(card=>card.onclick=()=>{filter=card.dataset.statusCard;$('#filter').value=filter;table();$('#stock-list').scrollIntoView({behavior:'smooth',block:'start'})})}if(view==='refill'){hint();$('#refill-drug').onchange=hint}bindForms()}
async function submit(form,path,data){let btn=form.querySelector('button[type=submit],button:not([type])');if(btn)btn.disabled=true;try{await api(path,data);message('บันทึกเรียบร้อยแล้ว');await load()}catch(e){message(e.message,true)}finally{if(btn)btn.disabled=false}}
function formData(f){return Object.fromEntries(new FormData(f))}
function bindForms(){
 for(let [id,path] of [['refill-form','/virtual-stock/api/refill'],['settings-form','/virtual-stock/api/settings'],['coverage-form','/virtual-stock/api/coverage']]){let f=document.getElementById(id);if(f)f.onsubmit=e=>{e.preventDefault();submit(f,path,formData(f))}}
 let cf=$('#central-form');if(cf)cf.onsubmit=async e=>{e.preventDefault();let b=cf.querySelector('button');b.disabled=true;try{let values=formData(cf);await OfflineStock.configure(values.url,values.key||undefined);message('เชื่อมต่อฐานข้อมูลกลางเรียบร้อยแล้ว');await load()}catch(error){message(error.message,true);await load()}finally{b.disabled=false}};
 let cr=$('#central-refresh');if(cr)cr.onclick=async()=>{cr.disabled=true;try{await OfflineStock.refresh();message('โหลดข้อมูลล่าสุดจากส่วนกลางแล้ว');await load()}catch(error){message(error.message,true);await load()}finally{cr.disabled=false}};
 let pf=$('#packs-form');if(pf)pf.onsubmit=e=>{e.preventDefault();submit(pf,'/virtual-stock/api/packs',formData(pf))};
 if($('#refill-import-file'))$('#refill-import-file').onchange=async e=>{let file=e.target.files[0];if(!file)return;$('#refill-import-preview').textContent='กำลังตรวจไฟล์…';try{let p;if(window.OfflineStock?.enabled())p=await OfflineStock.previewRefills(file);else{let r=await fetch('/virtual-stock/api/refill-import-preview?name='+encodeURIComponent(file.name),{method:'POST',headers:{'X-Stock-App':'1'},body:file});p=await r.json();if(!r.ok)throw Error(p.error)}$('#refill-import-preview').innerHTML=`<div class="notice teal" style="margin-top:18px"><b>${n(p.rows)} แถว · ${p.drugs} รายการยา · ${p.days} วันที่เบิก</b><br>${pretty(p.first)} – ${pretty(p.last)} · รวม ${n(p.total_packs)} แพ็ค${p.conflicts.length?`<br>พบ ${p.conflicts.length} รายการที่ยาและวันที่ซ้ำกับประวัติเดิม`:''}</div>${p.conflicts.length?`<label class="checkbox"><input id="replace-refill-import" type="checkbox">ยืนยันยกเลิกรายการเดิมแล้วใช้ข้อมูลจากไฟล์แทน (${esc(p.conflicts.join(', '))})</label>`:''}<button id="commit-refill-import">ยืนยันบันทึกการเบิกจากไฟล์</button>`;$('#commit-refill-import').onclick=async()=>{if(p.conflicts.length&&!$('#replace-refill-import').checked){message('กรุณายืนยันการแทนรายการเบิกเดิมก่อน',true);return}let btn=$('#commit-refill-import');btn.disabled=true;try{await api('/virtual-stock/api/refill-import-commit',{token:p.token,replace:!!$('#replace-refill-import')?.checked});message(`นำเข้าประวัติการเบิก ${p.drugs} รายการยา รวม ${n(p.total_packs)} แพ็คเรียบร้อยแล้ว`);await load()}catch(err){message(err.message,true);btn.disabled=false}}}catch(err){$('#refill-import-preview').innerHTML=`<div class="notice error" style="margin-top:16px">${esc(err.message)}</div>`}};
 if($('#import-file'))$('#import-file').onchange=async e=>{let file=e.target.files[0];if(!file)return;previewData=null;$('#import-preview').textContent='กำลังตรวจไฟล์…';try{let p;if(window.OfflineStock?.enabled())p=await OfflineStock.previewDaily(file);else{let r=await fetch('/virtual-stock/api/import-preview?name='+encodeURIComponent(file.name),{method:'POST',headers:{'X-Stock-App':'1'},body:file});p=await r.json();if(!r.ok)throw Error(p.error)}previewData=p;$('#import-preview').innerHTML=`<div class="notice teal" style="margin-top:18px"><b>${n(p.rows)} รายการ · ${p.drugs} ยา · ${p.days} วันที่มีรายการ</b><br>${pretty(p.first)} – ${pretty(p.last)} · รวม ${n(p.total,2)} หน่วย (หลายชนิดยา)<br>วันที่ยอดเหมือนเดิม ${p.unchanged} · วันที่ซ้ำและยอดเปลี่ยน ${p.conflicts.length} · ยาใหม่ ${p.new_drugs.length}</div>${p.conflicts.length?`<label class="checkbox"><input id="replace-import" type="checkbox">ยืนยันแทนยอดทั้งวัน ${esc(p.conflicts.join(', '))} ด้วยข้อมูลจากไฟล์นี้</label>`:''}<label class="checkbox"><input id="complete-import" type="checkbox">ตรวจสอบแล้วว่าข้อมูลครบช่วงนี้ วันที่ไม่มีรายการ ${p.gap_days} วันคือไม่มีการใช้จริง</label><label class="checkbox"><input id="full-import" type="checkbox">ไฟล์นี้มียอดครบทั้งวัน ไม่ใช่ไฟล์ข้อมูลบางส่วนของวัน</label><button id="commit-import">ยืนยันนำเข้า</button>`;$('#commit-import').onclick=async()=>{if(!$('#full-import').checked){message('กรุณายืนยันว่าไฟล์มียอดครบทั้งวันก่อนนำเข้า',true);return}if(p.conflicts.length&&!$('#replace-import').checked){message('กรุณายืนยันการแทนยอดวันที่ซ้ำ',true);return}let b={token:p.token,replace:!!$('#replace-import')?.checked,complete:$('#complete-import').checked};let btn=$('#commit-import');btn.disabled=true;try{await api('/virtual-stock/api/import-commit',b);previewData=null;message('นำเข้าเรียบร้อยแล้ว ยอดใช้จริงถูกปรับโดยไม่นับซ้ำ');await load()}catch(e){message(e.message,true);btn.disabled=false}}}catch(e){$('#import-preview').innerHTML=`<div class="notice error" style="margin-top:16px">${esc(e.message)}</div>`}};
}
document.addEventListener('click',async e=>{let b=e.target.closest('[data-view],[data-go],[data-refill],[data-void]');if(!b)return;e.preventDefault();if(b.dataset.void){if(!confirm('ยกเลิกประวัติการเบิกรายการนี้? ระบบจะคำนวณรอบเบิกใหม่'))return;try{await api('/virtual-stock/api/void-refill',{id:Number(b.dataset.void)});message('ยกเลิกรายการแล้ว');await load()}catch(err){message(err.message,true)}return}message('');view=b.dataset.view||b.dataset.go||'refill';render(b.dataset.refill)});
$('#asof').value=today();$('#asof').max=today();$('#asof').onchange=()=>{if($('#asof').value)load()};load();




